# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='cls_id',
            new_name='cls',
        ),
    ]
