# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '打分（1~10分）'), (2, '单选'), (3, '评论')]),
        ),
    ]
