# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20171207_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Option', verbose_name='单选答案'),
        ),
        migrations.AddField(
            model_name='answer',
            name='val',
            field=models.IntegerField(blank=True, null=True, verbose_name='打分答案'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文本答案'),
        ),
    ]
